language: csharp
mono: nightly
solution: MPM.sln
sudo: false
cache:
  directories:
    - packages
script:
  - xbuild /p:Configuration=Release /tv:4.0 MPM.sln
  - mono ./packages/xunit.runner.console.*/tools/xunit.console.exe ./MPMTest/bin/Release/MPMTest.dll
